---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3

suites:
  - name: centos7
    excludes:
      - centos-6.9
    verifier:
      inspec_tests:
          - name: centos7
            path: test/integration/centos7/inspec
    run_list:
      - recipe[yum_wrapper::add_repositories]
    data_path: './test/files'
    attributes: {
      "yum_wrapper" : {
        "repositories" : {
          "add" : {
              "artifactory-epel-el7" : {
                  "baseurl": "https://cida.usgs.gov/artifactory/EPEL/7/x86_64",
                  "gpgkey": "https://cida.usgs.gov/artifactory/EPEL/RPM-GPG-KEY-EPEL-7",
                  "repo_gpgcheck": false,
                  "gpgcheck": true
              },
              "artifactory-centos-73" : {
                  "baseurl": [
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/centosplus/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/cloud/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/contrib/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/cr/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/extras/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/fasttrack/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/isos/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/os/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/scio/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/storage/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/updates/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/7.3.1611/virt/x86_64"
                  ],
                  "gpgkey": "https://cida.usgs.gov/artifactory/centos/RPM-GPG-KEY-CentOS-7",
                  "repo_gpgcheck": false,
                  "gpgcheck": true
              }
          }
        }
      }
    }


  - name: centos6
    excludes:
      - centos-7.3
    verifier:
      inspec_tests:
          - name: centos6
            path: test/integration/centos6/inspec
    run_list:
      - recipe[yum_wrapper::add_repositories]
    data_path: './test/files'
    attributes: {
      "yum_wrapper" : {
        "repositories" : {
          "add" : {
              "artifactory-epel-el6" : {
                  "baseurl": "https://cida.usgs.gov/artifactory/EPEL/6/x86_64",
                  "gpgkey": "https://cida.usgs.gov/artifactory/EPEL/RPM-GPG-KEY-EPEL-6",
                  "repo_gpgcheck": false,
                  "gpgcheck": true
              },
              "artifactory-centos-69" : {
                  "baseurl": [
                    "https://cida.usgs.gov/artifactory/centos/6.9/centosplus/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/cloud/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/contrib/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/cr/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/extras/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/fasttrack/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/isos/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/os/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/scio/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/storage/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/updates/x86_64",
                    "https://cida.usgs.gov/artifactory/centos/6.9/virt/x86_64"
                  ],
                  "gpgkey": "https://cida.usgs.gov/artifactory/centos/RPM-GPG-KEY-CentOS-6",
                  "repo_gpgcheck": false,
                  "gpgcheck": true
              }
          }
        }
      }
    }
